<?php
/** @var \omSocialButtons\Buttons $this */
if (!current_user_can('manage_options'))
	wp_die(__('You do not have sufficient permissions to manage options for this site.', SB));
?>

<style type="text/css">
	h3 {
		border-bottom: 1px solid #ddd;
		padding-bottom: .2em;
	}

	pre {
		border: 1px solid #ddd;
		padding: 3px 8px;
		background: #eee;
	}
</style>

<div class="wrap">
	<?php screen_icon(); ?>
	<h2><?php _e('Social Buttons Settings', SB) ?></h2>

	<form action="<?php echo $action ?>" method="post">

		<table class="form-table">
			<tr>
				<td colspan="2"><h3><? _e('Common', SB) ?></h3></td>
			</tr>
			<tr oninvalid="top">
				<th scope="row"><?php _e('Add buttons', SB) ?></th>
				<td>
					<select name="add_button" id="add_button">
						<option value="manually" <?php selected('manually', $this->options->add_button); ?>>manually</option>
						<option value="before" <?php selected('before', $this->options->add_button); ?>>before</option>
						<option value="after" <?php selected('after', $this->options->add_button); ?>>after</option>
						<option value="both" <?php selected('both', $this->options->add_button); ?>>after & before</option>
					</select>
					<label for="add_button"><?php _e('content', SB) ?></label>
				</td>
			</tr>

			<?php if ($this->options->add_button === 'manually') { ?>
				<tr>
					<th><?php _e('Manualy', SB) ?></th>
					<td>
						<p><?php _e('Add somewhere to you single post template php file', SB) ?></p>

						<pre><? foreach ($this->buttons as $name => $button) {
								echo sprintf('echo $omSocialButtons->%s()->getButtonHtml();' . PHP_EOL, $name);
							} ?></pre>
						<p><? _e('or', SB) ?></p>
						<pre>echo $omSocialButtons->getButtonHtml();</pre>
					</td>
				</tr>
			<?php } ?>

			<tr>
				<th scope="row"><?php _e('Add to', SB) ?></th>
				<td>
					<?php
					$i = 1;
					foreach ($post_types as $post_type) {
						?>
						<label for="insert_to<?php echo '-' . $i ?>">
							<input name="insert_to[]" type="checkbox" id="insert_to<?php echo '-' . $i ?>"
							       value="<?php esc_attr_e($post_type->name) ?>"
								<?php if (in_array($post_type->name, (array)$this->options->insert_to)) echo 'checked="checked"' ?>/>
							<?php echo $post_type->labels->name ?></label><br>
						<?php $i++;
					}?>
				</td>
			</tr>

			<tr>
				<th scope="row"><? _e('Show buttons on', SB) ?></th>
				<td>
					<label for="on_single">
						<input name="on_single" type="checkbox" id="on_single" value="1" <?php checked(
							true, $this->options->on_single
						); ?> />
						<?php _e('single page or post', SB) ?>
					</label><br>

					<label for="on_archive">
						<input name="on_archive" type="checkbox" id="on_archive" value="1" <?php checked(
							true, $this->options->on_archive
						); ?> />
						<?php _e('archive page', SB) ?>
					</label><br>

					<label for="on_home">
						<input name="on_home" type="checkbox" id="on_home" value="1" <?php checked(
							true, $this->options->on_home
						); ?> />
						<?php _e('home page', SB) ?>
					</label>

				</td>
			</tr>

			<?php $this->getOptionsForm(); ?>

		</table>

		<?php submit_button(); ?>

	</form>

</div>
	