<?php
/** @var \omSocialButtons\Buttons $this */
if (!current_user_can('manage_options'))
	wp_die(__('You do not have sufficient permissions to manage options for this site.'));
?>

<style type="text/css">
	h3 {
		border-bottom: 1px solid #ddd;
		padding-bottom: .2em;
	}
</style>

<div class="wrap">
	<?php screen_icon(); ?>
	<h2><?php _e('Social Buttons Settings', 'oms')?></h2>

	<form action="<?php echo $action ?>" method="post">

		<table class="form-table">
			<tr>
				<td colspan="2"><h3>Common</h3></td>
			</tr>
			<tr oninvalid="top">
				<th scope="row"><?php _e('Add buttons') ?></th>
				<td>
					<select name="add_button" id="add_button">
						<option value="manually" <?php selected('manually', $this->options->add_button); ?>>manually</option>
						<option value="before" <?php selected('before', $this->options->add_button); ?>>before</option>
						<option value="after" <?php selected('after', $this->options->add_button); ?>>after</option>
						<option value="both" <?php selected('both', $this->options->add_button); ?>>both (after & before)</option>
					</select>
					<label for="add_button"><?php _e('content')?></label>
				</td>
			</tr>

			<?php if ($this->options->add_button === 'manually') { ?>
				<tr>
					<th><?php _e('Manualy')?></th>
					<td>
						<p><?php _e('Add somewhere to you single post template php file')?> </p>
						<pre>echo $omSocialButtons->facebook();</pre>
						<pre>echo $omSocialButtons->googleplus();</pre>
						<pre>echo $omSocialButtons->twitter();</pre>
					</td>
				</tr>
			<?php } ?>

			<tr>
				<th scope="row"><?php _e('Add to') ?></th>
				<td>
					<?php
					$i = 1;
					foreach ($post_types as $post_type) {
						?>
						<label for="insert_to<?php echo '-' . $i ?>">
							<input name="insert_to[]" type="checkbox" id="insert_to<?php echo '-' . $i ?>"
							       value="<?php esc_attr_e($post_type->name) ?>"
								<?php if (in_array($post_type->name, (array)$this->options->insert_to)) echo 'checked="checked"' ?>/>
							<?php echo $post_type->labels->name ?></label><br>
						<?php $i++;
					}?>
				</td>
			</tr>

			<?php $this->getOptionsForm(); ?>

		</table>

		<?php submit_button(); ?>

	</form>

</div>
	