<? /** @var \omSocialButtons\facebook\Facebook $this */ ?>
<? if ($this->root) { ?>
	<div id="fb-root"></div>
	<script>(function (d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s);
			js.id = id;
			js.src = "//connect.facebook.net/<?= $this->options->lang?>/all.js#xfbml=1&appId=556615607691233";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
<? } ?>
<? $this->root = false; ?>
<div class="facebook">
	<div class="fb-like" <?
	use omSocialButtons\Html;

	Html::attr('data-href', apply_filters('share_url', get_permalink()));
	Html::attr('data-colorscheme', $this->options->colorscheme);
	Html::attr('data-width', (int)$this->options->width);
	Html::attr('data-send', ($this->options->send) ? 'true' : null);
	Html::attr('data-show-faces', ($this->options->show_faces) ? 'true' : null);
	Html::attr('data-font', $this->options->font);
	Html::attr('data-action', $this->options->action);
	Html::attr('data-layout', $this->options->layout);
	?>></div>
</div>
