<? /** @var \omSocialButtons\twitter\Twitter $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2"><h3>Twitter</h3></td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Enable', SB) ?></th>
		<td>
			<label for="twitter_enable">
				<input name="twitter_enable" type="checkbox" id="twitter_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable button', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><label for="twitter_via"><?php _e('Twitter via', SB) ?></label></th>
		<td>
			<label for="twitter_via">@</label>
			<input name="twitter_via" type="text" id="twitter_via"
			       value="<?php echo esc_attr($this->options->via); ?>"
			       class="regular-text"/>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><label for="twitter_related"><?php _e('Related account', SB) ?></label></th>
		<td>
			<input name="twitter_related" type="text" id="twitter_related"
			       value="<?php echo esc_attr($this->options->related); ?>"
			       class="regular-text"/>

		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><label for="twitter_lang"><?php _e('Lang', SB) ?></label></th>
		<td>
			<select name="twitter_lang" id="twitter_lang">
				<?php foreach ($this->lang as $key => $name) { ?>
					<option value="<?php echo $key ?>" <?php selected($key, $this->options->lang); ?>><?php echo $name ?></option>
				<?php } ?>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><label for="twitter_text"><?php _e('Twitter text', SB) ?></label></th>
		<td>
			<input name="twitter_text" type="text" id="twitter_text"
			       value="<?php echo esc_attr($this->options->text); ?>"
			       class="regular-text"/>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Size', SB) ?></th>
		<td>
			<label for="twitter_size">
				<select name="twitter_size" id="twitter_count">
					<option value="" <?php selected('', $this->options->size); ?>>normal</option>
					<option value="large" <?php selected('large', $this->options->size); ?>>Large</option>
				</select>
		</td>
	</tr>

	<tr oninvalid="top">
		<th scope="row"><?php _e('Count', SB) ?></th>
		<td>
			<select name="twitter_count" id="twitter_count">
				<option value="" <?php selected('', $this->options->count); ?>>None</option>
				<option value="" <?php selected('', $this->options->count); ?>>None</option>
				<option value="horizontal" <?php selected('horizontal', $this->options->count); ?>>Horizontal</option>
				<option value="vertical" <?php selected('vertical', $this->options->count); ?>>Vertical</option>
			</select>
		</td>

	</tr>


	<tr valign="top">
		<th scope="row"><label for="twitter_hashtags"><?php _e('Twitter hashtags', SB) ?></label></th>
		<td>
			<input name="twitter_hashtags" type="text" id="twitter_hashtags"
			       value="<?php echo esc_attr($this->options->hashtags); ?>"
			       class="regular-text"/>
		</td>
	</tr>

	<tr>
		<th><?php _e('Example', SB); ?></th>
		<td><?php $this->getButtonHtml()?></td>
	</tr>

	<tr>
		<th><?php _e('More info about', SB) ?></th>
		<td><a href="https://dev.twitter.com/docs/tweet-button" target="_blank" class="button-secondary">Tweet
				button</a>
		</td>
	</tr>
</table>
