<? /** @var \omSocialButtons\facebook\Facebook $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2"><h3>Facebook</h3></td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Enable') ?></th>
		<td>
			<label for="facebook_enable">
				<input name="facebook_enable" type="checkbox" id="facebook_enable"
				       value="1" <?php checked('1', $this->options->enable); ?> />
				<?php _e('enable button') ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Width') ?></th>
		<td>
			<input name="facebook_width" type="text" id="facebook_width"
			       value="<?php echo esc_attr($this->options->width); ?>"
			       class="regular-text"/>
			<label for="facebook_width">px</label>

		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Send button') ?></th>
		<td>
			<label for="facebook_send">
				<input name="facebook_send" type="checkbox" id="facebook_send"
				       value="1" <?php checked('1', $this->options->send); ?> />
				<?php _e('send button') ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Show faces', 'oms') ?></th>
		<td>
			<label for="facebook_show_faces">
				<input name="facebook_show_faces" type="checkbox" id="facebook_show_faces"
				       value="1" <?php checked('1', $this->options->show_faces); ?> />
				<?php _e('show faces', 'oms') ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Color scheme', 'oms') ?></th>
		<td>
			<select name="facebook_colorscheme" id="facebook_colorscheme">
				<option value="" <?php selected($this->options->colorscheme, ''); ?>>Light</option>
				<option value="dark" <?php selected($this->options->colorscheme, 'dark'); ?>>Dark</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Layout') ?></th>
		<td>
			<select name="facebook_layout" id="facebook_layout">
				<option value="" <?php selected($this->options->layout, ''); ?>>standard</option>
				<option value="button_count" <?php selected($this->options->layout, 'button_count'); ?>>button_count</option>
				<option value="box_count" <?php selected($this->options->layout, 'box_count'); ?>>box_count</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Font') ?></th>
		<td>
			<select name="facebook_font" id="facebook_font">
				<option value="" <?php selected($this->options->font, ''); ?>></option>
				<option value="arial" <?php selected($this->options->font, 'arial'); ?>>arial</option>
				<option value="lucida grande" <?php selected($this->options->font, 'lucida grande'); ?>>lucida grande</option>
				<option value="segoe ui" <?php selected($this->options->font, 'segoe ui'); ?>>segoe ui</option>
				<option value="tahoma" <?php selected($this->options->font, 'tahoma'); ?>>tahoma</option>
				<option value="trebuchet ms" <?php selected($this->options->font, 'trebuchet ms'); ?>>trebuchet ms</option>
				<option value="verdana" <?php selected($this->options->font, 'verdana'); ?>>verdana</option>
			</select>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Action') ?></th>
		<td>
			<select name="facebook_action" id="facebook_action">
				<option value="" <?php selected($this->options->action, ''); ?>>like</option>
				<option value="recommend" <?php selected($this->options->action, 'recommend'); ?>>recommend</option>
			</select>
		</td>
	</tr>

	<tr>
		<th><?php _e('Example'); ?></th>
		<td><?php $this->getButtonHtml(); ?></td>
	</tr>

	<tr>
		<th><?php _e('More info about') ?></th>
		<td>
			<a href="https://developers.facebook.com/docs/reference/plugins/like/" target="_blank"
			   class="button-secondary">Facebook button</a>
		</td>
	</tr>
</table>
