<? /** @var \omSocialButtons\facebook\Facebook $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2"><h3>Flatter</h3></td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Enable', SB) ?></th>
		<td>
			<label for="flatter_enable">
				<input name="flatter_enable" type="checkbox" id="flatter_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable button', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Width', SB) ?></th>
		<td>
			<input name="flatter_width" type="text" id="flatter_width"
			       value="<?php echo esc_attr($this->options->width); ?>"
			       class="regular-text"/>
			<label for="flatter_width">px</label>

		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Send button', SB) ?></th>
		<td>
			<label for="flatter_send">
				<input name="flatter_send" type="checkbox" id="flatter_send"
				       value="1" <?php checked(true, $this->options->send); ?> />
				<?php _e('send button', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Show faces', SB) ?></th>
		<td>
			<label for="flatter_show_faces">
				<input name="flatter_show_faces" type="checkbox" id="flatter_show_faces"
				       value="1" <?php checked(true, $this->options->show_faces); ?> />
				<?php _e('show faces', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Color scheme', SB) ?></th>
		<td>
			<select name="flatter_colorscheme" id="flatter_colorscheme">
				<option value="" <?php selected('', $this->options->colorscheme); ?>>Light</option>
				<option value="dark" <?php selected('dark', $this->options->colorscheme); ?>>Dark</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Layout', SB) ?></th>
		<td>
			<select name="flatter_layout" id="flatter_layout">
				<option value="" <?php selected('', $this->options->layout); ?>>standard</option>
				<option value="button_count" <?php selected('button_count', $this->options->layout); ?>>button_count</option>
				<option value="box_count" <?php selected('box_count', $this->options->layout); ?>>box_count</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Font', SB) ?></th>
		<td>
			<select name="flatter_font" id="flatter_font">
				<option value="" <?php selected('', $this->options->font); ?>></option>
				<option value="arial" <?php selected('arial', $this->options->font); ?>>arial</option>
				<option value="lucida grande" <?php selected('lucida grande', $this->options->font); ?>>lucida grande</option>
				<option value="segoe ui" <?php selected('segoe ui', $this->options->font); ?>>segoe ui</option>
				<option value="tahoma" <?php selected('tahoma', $this->options->font); ?>>tahoma</option>
				<option value="trebuchet ms" <?php selected('trebuchet ms', $this->options->font); ?>>trebuchet ms</option>
				<option value="verdana" <?php selected('verdana', $this->options->font); ?>>verdana</option>
			</select>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Action', SB) ?></th>
		<td>
			<select name="flatter_action" id="flatter_action">
				<option value="" <?php selected($this->options->action, ''); ?>>like</option>
				<option value="recommend" <?php selected($this->options->action, 'recommend'); ?>>recommend</option>
			</select>
		</td>
	</tr>



	<tr>
		<th><?php _e('Example', SB); ?></th>
		<td><?php $this->getButtonHtml();?></td>
	</tr>

	<tr>
		<th><?php _e('More info about', SB) ?></th>
		<td>
			<a href="https://developers.facebook.com/docs/reference/plugins/like/" target="_blank"
			   class="button-secondary">Facebook button</a>
		</td>
	</tr>
</table>
