<? /** @var \omSocialButtons\flatter\Flatter $this */ ?>
<table class="form-table">
	<tr>
		<td colspan="2"><h3>Flatter</h3></td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Enable', SB) ?></th>
		<td>
			<label for="flatter_enable">
				<input name="flatter_enable" type="checkbox" id="flatter_enable"
				       value="1" <?php checked(true, $this->options->enable); ?> />
				<?php _e('enable button', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Mode', SB) ?></th>
		<td>
			<select name="flatter_mode" id="flatter_mode">
				<option value="" <?php selected('', $this->options->mode); ?>>Auto</option>
				<option value="manual" <?php selected('manual', $this->options->mode); ?>>Manual</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('HTTPS', SB) ?></th>
		<td>
			<label for="flatter_https">
				<input name="flatter_https" type="checkbox" id="flatter_https"
				       value="1" <?php checked(true, $this->options->https); ?> />
				<?php _e('use https', SB) ?></label>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Popout', SB) ?></th>
		<td>
			<label for="flatter_popout">
				<input name="flatter_popout" type="checkbox" id="flatter_popout"
				       value="1" <?php checked(true, $this->options->popout); ?> />
				<?php _e('show popout when hovering mouse over button', SB) ?></label>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('UID', SB) ?></th>
		<td>
			<input name="flatter_uid" type="text" id="flatter_uid"
			       value="<?= esc_attr($this->options->uid); ?>"
			       class="regular-text"/>

			<p class="description"><? _e('A Flattr username', SB) ?></p>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Button', SB) ?></th>
		<td>
			<select name="flatter_button" id="flatter_button">
				<option value="" <?php selected('', $this->options->button); ?>><?= __('Default', SB) ?></option>
				<option value="compact" <?php selected('compact', $this->options->button); ?>>Compact</option>
			</select>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Tags', SB) ?></th>
		<td>
			<input name="flatter_tags" type="text" id="flatter_tags" value="<?= esc_attr($this->options->tags); ?>"
			       class="regular-text"/>

			<p class="description"><? _e('Coma separated tags or leave empty for autofill by post tags', SB) ?></p>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Description', SB) ?></th>
		<td>
			<input name="flatter_description" type="text" id="flatter_description"
			       value="<?= $this->options->description ?>"
			       class="regular-text"/>

			<p class="description"><? _e('Description ', SB) ?></p>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Lang', SB) ?></th>
		<td>
			<select name="flatter_lang" id="flatter_lang">
				<?php foreach ($this->lang as $key => $name) { ?>
					<option value="<?= $key ?>" <?php selected($key, $this->options->lang); ?>><?= $name ?></option>
				<?php } ?>
			</select>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Category', SB) ?></th>
		<td>
			<select name="flatter_category" id="flatter_category">
				<?php foreach ($this->categories as $key => $name) { ?>
					<option value="<?= $key ?>" <?php selected($key, $this->options->category); ?>><?= $name ?></option>
				<?php } ?>
			</select>
		</td>
	</tr>

	<tr>
		<th><?php _e('Example', SB); ?></th>
		<td><?php $this->getButtonHtml(); ?></td>
	</tr>

	<tr>
		<th><?php _e('More info about', SB) ?></th>
		<td>
			<a href="http://developers.flattr.net/button/" target="_blank"
			   class="button-secondary">Flatter button</a>
		</td>
	</tr>


</table>