<?php /** @var $this \omSocialButtons\google\GooglePlus */ ?>
<table class="form-table">
	<tr>
		<td colspan="2"><h3>Google plus</h3></td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Enable', SB) ?></th>
		<td>
			<label for="googleplus_enable">
				<input name="googleplus_enable" type="checkbox" id="googleplus_enable"
				       value="1" <?php checked(true, $this->isEnable()); ?> />
				<?php _e('enable button', SB) ?></label>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Size', SB) ?></th>
		<td>
			<select name="googleplus_size" id="googleplus_size">
				<option value="small" <?php selected($this->options->size, 'small'); ?>>Small</option>
				<option value="medium" <?php selected($this->options->size, 'medium'); ?>>Medium</option>
				<option value="" <?php selected($this->options->size, ''); ?>>Normal</option>
				<option value="tall" <?php selected($this->options->size, 'tall'); ?>>Tall</option>
			</select>
		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><?php _e('Annotation', SB) ?></th>
		<td>
			<select name="googleplus_annotation" id="googleplus_annotation">
				<option value="inline" <?php selected($this->options->annotation, 'inline'); ?>>Inline</option>
				<option value="" <?php selected($this->options->annotation, ''); ?>>Bubble</option>
				<option value="none" <?php selected($this->options->annotation, 'none'); ?>>None</option>
			</select>
		</td>
	</tr>


	<tr valign="top">
		<th scope="row"><?php _e('Width', SB) ?></th>
		<td>
			<input name="googleplus_width" type="text" id="googleplus_width"
			       value="<?php echo esc_attr($this->options->width); ?>"
			       class="regular-text"/>
			<label for="googleplus_width">px</label>

		</td>
	</tr>

	<tr valign="top">
		<th scope="row"><label for="googleplus_lang"><?php _e('Lang', SB) ?></label></th>
		<td>
			<select name="googleplus_lang" id="googleplus_lang">
				<?php foreach ($this->lang as $key => $name) { ?>
					<option value="<?php echo $key ?>" <?php selected($key, $this->options->lang); ?>><?php echo $name ?></option>
				<?php } ?>
			</select>
		</td>
	</tr>

	<tr>
		<th><?php _e('Example', SB); ?></th>
		<td><?php $this->getButtonHtml(); ?></td>
	</tr>

	<tr>
		<th><?php _e('More info about', SB) ?></th>
		<td><a href="https://developers.google.com/+/plugins/+1button/" target="_blank" class="button-secondary">Google+
				button</a>
		</td>
	</tr>


</table>