<div class="twitter">
    <a href="https://twitter.com/share" class="twitter-share-button"<?php
	    SocialButtons::attr('data-via', $twitter_via);
	    SocialButtons::attr('data-related', $twitter_related);
	    SocialButtons::attr('data-url', $permalink);
	    SocialButtons::attr('data-lang', $twitter_lang);
	    SocialButtons::attr('data-text', get_the_title() . $twitter_text);
	    SocialButtons::attr('data-size', ($twitter_size) ? 'large' : null);
	    SocialButtons::attr('data-count', $twitter_count);
	    SocialButtons::attr('data-hashtags', $twitter_hashtags);
	    ?>></a>
    <script>!function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (!d.getElementById(id)) {
            js = d.createElement(s);
            js.id = id;
            js.src = "//platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);
        }
    }(document, "script", "twitter-wjs");</script>
</div>